# Generated by Django 2.2 on 2019-04-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_subscription_gym'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='client_name',
            new_name='client',
        ),
    ]
