# Generated by Django 2.2 on 2019-05-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190507_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'coach', 'verbose_name_plural': 'coaches'},
        ),
    ]
