# Generated by Django 2.2 on 2019-04-26 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('experience', models.IntegerField()),
                ('work_days', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('duration', models.CharField(max_length=200)),
                ('has_coach', models.BooleanField(default=False)),
                ('allowed_from', models.TimeField()),
                ('allowed_until', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.FloatField()),
                ('chest_girth', models.FloatField()),
                ('waist_circumference', models.FloatField()),
                ('hip_girth', models.FloatField()),
                ('body_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('registered_date', models.DateTimeField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Coach')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Test')),
            ],
        ),
    ]
