# Generated by Django 2.2 on 2019-04-26 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190426_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='client_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Client'),
        ),
    ]
