# Generated by Django 2.2 on 2019-04-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190426_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_of',
            new_name='feedback_to',
        ),
    ]
