# Generated by Django 2.2 on 2019-04-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190426_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_of',
            new_name='gym',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='coach_of',
            new_name='gym',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_to',
            new_name='gym',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_of',
            new_name='gym',
        ),
    ]
