# Generated by Django 2.2 on 2019-04-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190427_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='gym',
        ),
    ]
