# Generated by Django 2.2 on 2019-05-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_gym_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='image',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='image',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]
