# Generated by Django 2.2 on 2019-05-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190507_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='photo',
        ),
    ]
