# Generated by Django 2.2 on 2019-05-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190507_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
