# Generated by Django 2.2 on 2019-05-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_client_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
    ]
